name: Cap nhat thuy van IWE

on:
  workflow_dispatch:
  schedule:
    # 00:00 UTC tương ứng với 07:00 AM giờ Việt Nam
    - cron: '0 0 * * *'

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas pdfplumber
      - name: Run Scraper
        run: python main.py
