name: Cap nhat thuy van IWE
on:
  workflow_dispatch: 
  schedule:
    - cron: */5 * * * *' # Chạy mỗi 5 phút một lần

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Nâng cấp lên v4 để hết cảnh báo
      - name: Set up Python
        uses: actions/setup-python@v5 # Nâng cấp lên v5 để hết cảnh báo
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas pdfplumber
      - name: Run Scraper
        run: python main.py
